# Generated by Django 5.1.3 on 2024-11-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_form', '0005_predict_delete_feedback_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDS_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.IntegerField()),
                ('question2', models.IntegerField()),
                ('question3', models.IntegerField()),
                ('question4', models.IntegerField()),
                ('question5', models.IntegerField()),
                ('question6', models.IntegerField()),
                ('question7', models.IntegerField()),
                ('question', models.CharField(max_length=240)),
            ],
        ),
        migrations.DeleteModel(
            name='predict',
        ),
    ]
